### PR TITLE
[IAP]Demo of in-app purchase extension.

### PR DESCRIPTION
**Pull request by minggangw**
This patch demos how to use the in-app purchase(IAP) to finish buying
goods on Apple Store. The interfaces used includes:
- init
- queryProductsInfo
- purchase
- getReceipt
- validateReceipt
- restore

BUG=XWALK-5698

### CODE REVIEW

**Comment by minggangw** [comment]
@jondong Please review this PR, thanks!

**Comment by minggangw** [comment]
PR updated, @jondong please review.

**Comment by minggangw** [comment]
PR updated, @jondong please review.

**Comment by jondong** [comment]
lgtm

**Pull request merged**
